name: Mi primer GitHub Actions
on:
  push:
    branches:
      - 'main'
    paths:
      - 'hello-world.py'
jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
        - name: checkout-repo
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        
        - name: Print Hello World
          run: python hello-world.py

